[package]
name = "gbrt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn-clone = "1.0.10"
image = "0.24.5"
rand = "0.8.5"
