constants:
  width: 1920
  height: 1080
  samplesPerPixel: 32
  maxDepth: 5000
  minDepth: 5
  environmentMap: "skyboxes/winter_forest.jpg"
  environmentDistance: 30.0
  filter: "LanczosFilter"

camera:
  lookFrom: [0.0, 2.5, -20.0]
  lookAt: [0.0, 2.5, 0.0]
  vup: [0.0, 1.0, 0.0]
  vfov: 40.0
  aspectRatio: 1.777777
  aperture: 0.1
  focusDistance: 20.0

world: [
  {
    # A Sphere Reflecting the HDR
    objType: "Sphere",
    center: [0.0, 2.5, 1.0],
    radius: 2.5,
    material: {
      matType: "Dielectric",
      texType: "SolidColor",
      texture: { albedo: [0.9, 0.9, 0.9] },
      fuzz: 0.0,
      refractionIdx: 1.5,
    }
  },
  {
    # A Ground Sphere in the Room
    objType: "Sphere",
    center: [0.0, -30.0, 0.0],
    radius: 30.0,
    material: {
      matType: "Lambertian",
      texType: "ImageTexture",
      texture: { filename: "skyboxes/winter_forest.jpg" }
    }
  },
]
