constants:
  width: 1920
  height: 1080
  samplesPerPixel: 32
  maxDepth: 5000
  environmentMap: "skyboxes/milky_way.jpg"
  environmentDistance: 30.0

camera:
  lookFrom: [0.0, 2.5, -20.0]
  lookAt: [0.0, 2.5, 0.0]
  vup: [0.0, 1.0, 0.0]
  vfov: 40.0
  aspectRatio: 1.777777
  aperture: 0.1
  focusDistance: 20.0

world: [
  {
    # A Sphere Reflecting the HDR
    objType: "Sphere",
    center: [0.0, 2.5, 1.0],
    radius: 2.5,
    material: {
      matType: "Metal",
      texType: "SolidColor",
      texture: { albedo: [0.7, 0.6, 0.5] },
      fuzz: 0.0
    }
  },
]
