constants:
  width: 800
  height: 800
  samplesPerPixel: 32
  maxDepth: 5
  minDepth: 2
  sourcesLambda: 0.122364268571 # f = 2.45GHz
  powerRenderCenter: [-1.5, 2.5, -0.5] # -15;15|0;5|-15;15

camera:
  lookFrom: [-5.5, 12.0, 5.0]
  lookAt: [-1.5, 3.0, -0.5]
  vup: [0.0, 1.0, 0.0]
  vfov: 90.0
  aspectRatio: 1.0
  aperture: 0.1
  focusDistance: 10.0

world: [
  {
    # A Ground Object
    objType: "XZRectangle",
    position: [0.0, 0.0, 0.0],
    width: 20.0,
    height: 20.0,
    material: {
      matType: "Lambertian",
      texType: "SolidColor",
      texture: { albedo: [0.2, 0.2, 0.2] },
      # scale: 2.0,
    }
  },
  {
    # A Light Object
    objType: "Sphere",
    center: [0.0, 2.5, 0.0],
    radius: 0.4,
    material: {
      matType: "DiffuseLight",
      texType: "SolidColor",
      texture: { albedo: [1.0, 1.0, 1.0] }, # Property of SolidColor
      intensity: 10.0 # Property of DiffuseLight
    }
  },
  { # Right Wall
    objType: "YZRectangle",
    position: [3.5, 0.0, 0.0],
    width: 10.0,
    height: 9.0,
    material: {
      matType: "Lambertian",
      texType: "SolidColor",
      texture: { albedo: [0.2, 0.2, 0.2] },
    }
  },
  { # Left Wall
    objType: "YZRectangle",
    position: [-3.5, 0.0, -1.0],
    width: 10.0,
    height: 5.0,
    material: {
      matType: "Lambertian",
      texType: "SolidColor",
      texture: { albedo: [0.2, 0.2, 0.2] },
    }
  },
  { # Behind Wall
    objType: "XYRectangle",
    position: [-1.5, 0.0, 4.5],
    width: 10.0,
    height: 10.0,
    material: {
      matType: "Lambertian",
      texType: "SolidColor",
      texture: { albedo: [0.2, 0.2, 0.2] },
    }
  },
  { # Kitchen Left Wall
    objType: "YZRectangle",
    position: [-6.5, 0.0, 3.0],
    width: 10.0,
    height: 3.0,
    material: {
      matType: "Lambertian",
      texType: "SolidColor",
      texture: { albedo: [0.2, 0.2, 0.2] },
    }
  },
  { # Front Kitchen Wall
    objType: "XYRectangle",
    position: [-5.0, 0.0, 1.5],
    width: 3.0,
    height: 10.0,
    material: {
      matType: "Lambertian",
      texType: "SolidColor",
      texture: { albedo: [0.2, 0.2, 0.2] },
    }
  },
  { # Front Wall
    objType: "XYRectangle",
    position: [1.0, 0.0, -4.5],
    width: 5.0,
    height: 10.0,
    material: {
      matType: "Lambertian",
      texType: "SolidColor",
      texture: { albedo: [0.2, 0.2, 0.2] },
    }
  },
  { # Corridoio Right Wall (Door)
    objType: "YZRectangle",
    position: [-1.5, 0.0, -5.0],
    width: 10.0,
    height: 1.0,
    material: {
      matType: "Lambertian",
      texType: "SolidColor",
      texture: { albedo: [0.2, 0.2, 0.2] },
    }
  },
  { # Corridoio Left Wall (Fine del corridoio)
    objType: "YZRectangle",
    position: [-6.5, 0.0, -4.5],
    width: 10.0,
    height: 2.0,
    material: {
      matType: "Lambertian",
      texType: "SolidColor",
      texture: { albedo: [0.2, 0.2, 0.2] },
    }
  },
  { # Corridoio Front Wall
    objType: "XYRectangle",
    position: [-4.0, 0.0, -5.5],
    width: 5.0,
    height: 10.0,
    material: {
      matType: "Lambertian",
      texType: "SolidColor",
      texture: { albedo: [0.2, 0.2, 0.2] },
    }
  },
  { # Corridoio Behind Wall
    objType: "XYRectangle",
    position: [-5.0, 0.0, -3.5],
    width: 3.0,
    height: 10.0,
    material: {
      matType: "Lambertian",
      texType: "SolidColor",
      texture: { albedo: [0.2, 0.2, 0.2] },
    }
  },
]
