constants:
  width: 800
  height: 800
  samplesPerPixel: 100
  maxDepth: 5000
  backgroundColor: [0.0, 0.0, 0.0]

camera:
  lookFrom: [278.0, 278.0, -800.0]
  lookAt: [278.0, 278.0, 0.0]
  vup: [0.0, 1.0, 0.0]
  vfov: 40.0
  aspectRatio: 1.0
  aperture: 0.1
  focusDistance: 300.0

world: [
  {
    # A Left Wall Rectangle
    objType: "YZRectangle",
    position: [555.0, 277.5, 277.5],
    width: 555.0,
    height: 555.0,
    flipNormals: false,
    material: {
      matType: "Lambertian",
      albedo: [0.12, 0.45, 0.15]
    }
  },
  {
    # A Right Wall Rectangle
    objType: "YZRectangle",
    position: [0.0, 277.5, 277.5],
    width: 555.0,
    height: 555.0,
    flipNormals: false,
    material: {
      matType: "Lambertian",
      albedo: [0.66, 0.05, 0.05]
    }
  },
  {
    # A Light Rectangle
    objType: "XZRectangle",
    position: [278.0, 554.0, 279.5],
    width: 130.0,
    height: 115.0,
    flipNormals: true,
    material: {
      matType: "DiffuseLight",
      emittance: [15.0, 15.0, 15.0]
    }
  },
  {
    # A Floor Rectangle
    objType: "XZRectangle",
    position: [277.5, 0.0, 277.5],
    width: 555.0,
    height: 555.0,
    flipNormals: false,
    material: {
      matType: "Lambertian",
      albedo: [0.73, 0.73, 0.73]
    }
  },
  {
    # A RoofTop Rectangle
    objType: "XZRectangle",
    position: [277.5, 555.0, 277.5],
    width: 555.0,
    height: 555.0,
    flipNormals: false,
    material: {
      matType: "Lambertian",
      albedo: [0.73, 0.73, 0.73]
    }
  },
  {
    # A Front Wall
    objType: "XYRectangle",
    position: [277.5, 277.5, 555.0],
    width: 555.0,
    height: 555.0,
    flipNormals: false,
    material: {
      matType: "Lambertian",
      albedo: [0.73, 0.73, 0.73]
    }
  },
  {
    # A Lambertian White Box
    objType: "Box",
    position: [212.5, 82.5, 147.5],
    width: 165.0,
    height: 165.0,
    depth: 165.0,
    material: {
      matType: "Lambertian",
      albedo: [0.73, 0.73, 0.73]
    }
  },
  {
    # Another Lambertian White Box
    objType: "Box",
    position: [347.5, 165.0, 377.5],
    width: 165.0,
    height: 330.0,
    depth: 165.0,
    material: {
      matType: "Lambertian",
      albedo: [0.73, 0.73, 0.73]
    }
  }
]
