constants:
  width: 800
  height: 800
  samplesPerPixel: 32
  maxDepth: 5000

camera:
  lookFrom: [278.0, 278.0, -800.0]
  lookAt: [278.0, 278.0, 0.0]
  vup: [0.0, 1.0, 0.0]
  vfov: 40.0
  aspectRatio: 1.0
  aperture: 0.1
  focusDistance: 300.0

world: [
  {
    # A Left Wall Rectangle
    objType: "YZRectangle",
    position: [555.0, 277.5, 277.5],
    width: 555.0,
    height: 555.0,
    material: {
      matType: "Lambertian",
      texType: "SolidColor",
      albedo: [0.12, 0.45, 0.15]
    }
  },
  {
    # A Right Wall Rectangle
    objType: "YZRectangle",
    position: [0.0, 277.5, 277.5],
    width: 555.0,
    height: 555.0,
    material: {
      matType: "Lambertian",
      texType: "SolidColor",
      albedo: [0.66, 0.05, 0.05]
    }
  },
  {
    # A Light Rectangle
    objType: "XZRectangle",
    position: [278.0, 554.0, 279.5],
    width: 130.0,
    height: 115.0,
    material: {
      matType: "DiffuseLight",
      texType: "SolidColor",
      albedo: [1.0, 1.0, 1.0],
      intensity: 15.0
    }
  },
  {
    # A Floor Rectangle
    objType: "XZRectangle",
    position: [277.5, 0.0, 277.5],
    width: 555.0,
    height: 555.0,
    material: {
      matType: "Lambertian",
      texType: "SolidColor",
      albedo: [0.73, 0.73, 0.73]
    }
  },
  {
    # A RoofTop Rectangle
    objType: "XZRectangle",
    position: [277.5, 555.0, 277.5],
    width: 555.0,
    height: 555.0,
    material: {
      matType: "Lambertian",
      texType: "SolidColor",
      albedo: [0.73, 0.73, 0.73]
    }
  },
  {
    # A Front Wall
    objType: "XYRectangle",
    position: [277.5, 277.5, 555.0],
    width: 555.0,
    height: 555.0,
    material: {
      matType: "Lambertian",
      texType: "ChessBoard",
      albedo1: [0.73, 0.73, 0.73],
      albedo2: [0.2, 0.2, 0.2],
      scale: 0.1
    }
  },
  {
    # A Box in the Room
    objType: "Box",
    position: [450.0, 150.0, 190.0],
    width: 150.0,
    height: 300.0,
    depth: 150.0,
    material: {
      matType: "Metal",
      texType: "SolidColor",
      albedo: [0.9, 0.1, 0.1],
      fuzz: 0.1
    }
  },
  {
    # Another Box in the Room
    objType: "Box",
    position: [100.0, 100.0, 190.0],
    width: 150.0,
    height: 200.0,
    depth: 150.0,
    material: {
      matType: "Metal",
      texType: "ChessBoard",
      albedo1: [0.2, 0.85, 0.2],
      albedo2: [0.2, 0.2, 0.85],
      scale: 0.1,
      fuzz: 0.1
    }
  }
]
