constants:
  width: 1920
  height: 1080
  samplesPerPixel: 128
  maxDepth: 5000

camera:
  lookFrom: [0.0, 7.0, 8.0]
  lookAt: [0.0, 0.0, 0.0]
  vup: [0.0, 1.0, 0.0]
  vfov: 90.0
  aspectRatio: 1.77777777778 # 16.0 / 9.0
  aperture: 0.1
  focusDistance: 10.0

world: [
  {
    # A Ground Object
    objType: "Sphere",
    center: [0.0, -1000.0, 0.0],
    radius: 1000.0,
    material: {
      matType: "Lambertian",
      texType: "SolidColor",
      albedo: [0.2, 0.2, 0.2]
    }
  },
  {
    # A Light Object
    objType: "Sphere",
    center: [5.0, 7.0, -5.0],
    radius: 2.0,
    material: {
      matType: "DiffuseLight",
      # Basically like a Lambertian but has an emittance instead of an albedo
      # Albedo : [r, g, b] => r ∈ [0.0, 1.0), g ∈ [0.0, 1.0), b ∈ [0.0, 1.0)
      # Emit : [r, g, b] => r ∈ [0.0, +∞), g ∈ [0.0, +∞), g ∈ [0.0, +∞)
      emittance: [9.2, 9.2, 9.2]
    }
  },
  {
    objType: "Mesh",
    position: [0.0, 0.0, 5.0],
    scalingFactor: 4.0,
    rotation: [-90.0, 0.0, 0.0], # 90, 90, 220 [ Yaw, Roll, Pitch ]
    filename: "models/drinking_glass.stl",
    material: {
      matType: "Dielectric",
      refractionIdx: 1.5
    }
  }
]
