constants:
  width: 1920
  height: 1080
  samplesPerPixel: 32
  maxDepth: 5000

camera:
  lookFrom: [0.0, 6.0, 14.0]
  lookAt: [0.0, 0.0, 0.0]
  vup: [0.0, 1.0, 0.0]
  vfov: 90.0
  aspectRatio: 1.77777777778 # 16.0 / 9.0
  aperture: 0.1
  focusDistance: 10.0

world: [
  {
    # A Ground Object
    objType: "Sphere",
    center: [0.0, -1000.0, 0.0],
    radius: 1000.0,
    material: {
      matType: "Lambertian",
      texType: "SolidColor",
      albedo: [0.2, 0.2, 0.2]
    }
  },
  {
    # A Light Object
    objType: "Sphere",
    center: [7.5, 10.0, 3.0],
    radius: 2.0,
    material: {
      matType: "DiffuseLight",
      texType: "SolidColor",
      albedo: [1.0, 1.0, 1.0],
      intensity: 9.2
    }
  },
  {
    objType: "Mesh",
    position: [0.0, 5.0, 3.0],
    scalingFactor: 10.0,
    rotation: [140.0, 120.0, 220.0], # 90, 90, 220 [ Yaw, Roll, Pitch ]
    filename: "models/jet/jet2.obj",
    material: {
      matType: "Metal",
      texType: "SolidColor",
      albedo: [0.2, 0.2, 0.2],
      fuzz: 0.3
    }
  }
]
