constants:
  width: 800
  height: 800
  samplesPerPixel: 32
  maxDepth: 128

camera:
  lookFrom: [0.0, 2.5, -10.0]
  lookAt: [0.0, 2.5, 0.0]
  vup: [0.0, 1.0, 0.0]
  vfov: 40.0
  aspectRatio: 1.0
  aperture: 0.1
  focusDistance: 10.0

world: [
  {
    # A Left Wall Rectangle
    objType: "YZRectangle",
    position: [-10.0, 0.0, 0.0],
    width: 20.0,
    height: 20.0,
    material: {
      matType: "Lambertian",
      texType: "ImageTexture",
      filename: "skyboxes/yokohama/negx.jpg"
    }
  },
  {
    # A Right Wall Rectangle
    objType: "YZRectangle",
    position: [10.0, 0.0, 0.0],
    width: 20.0,
    height: 20.0,
    material: {
      matType: "Lambertian",
      texType: "ImageTexture",
      filename: "skyboxes/yokohama/posx.jpg"
    }
  },
  {
    # A Floor Rectangle
    objType: "XZRectangle",
    position: [0.0, -10.0, 0.0],
    width: 20.0,
    height: 20.0,
    material: {
      matType: "Lambertian",
      texType: "ImageTexture",
      filename: "skyboxes/yokohama/negy.jpg"
    }
  },
  {
    # A RoofTop Rectangle
    objType: "XZRectangle",
    position: [0.0, 10.0, 0.0],
    width: 20.0,
    height: 20.0,
    material: {
      matType: "Lambertian",
      texType: "ImageTexture",
      filename: "skyboxes/yokohama/posy.jpg"
    }
  },
  {
    # A Light Source Rectangle on the RoofTop
    objType: "XZRectangle",
    position: [0.0, 9.9, 0.0],
    width: 7.0,
    height: 7.0,
    material: {
      matType: "DiffuseLight",
      texType: "SolidColor",
      emittance: [15.0, 15.0, 15.0]
    }
  },
  {
    # A Front Wall
    objType: "XYRectangle",
    position: [0.0, 0.0, 10.0],
    width: 20.0,
    height: 20.0,
    material: {
      matType: "Lambertian",
      texType: "ImageTexture",
      filename: "skyboxes/yokohama/posz.jpg"
    }
  },
  {
    # A Back Wall
    objType: "XYRectangle",
    position: [0.0, 0.0, -10.0],
    width: 20.0,
    height: 20.0,
    material: {
      matType: "Lambertian",
      texType: "ImageTexture",
      filename: "skyboxes/yokohama/negz.jpg"
    }
  },
  {
    # A Box in the Room
    objType: "Sphere",
    center: [0.0, 2.5, 1.0],
    radius: 2.5,
    material: {
      matType: "Metal",
      texType: "SolidColor",
      albedo: [0.7, 0.6, 0.5],
      fuzz: 0.0
    }
  },
]
