constants:
  width: 1920
  height: 1080
  samplesPerPixel: 8
  maxDepth: 5000
  environmentMap: "skyboxes/arches/Arches_E_PineTree_8k.jpg" # Optional parameter, will fallback to a blue default skybox if not set

camera:
  lookFrom: [0.0, 6.0, 14.0]
  lookAt: [0.0, 0.0, 0.0]
  vup: [0.0, 1.0, 0.0]
  vfov: 90.0
  aspectRatio: 1.77777 # 1920.0 / 1080.0
  aperture: 0.1
  focusDistance: 10.0

world: [
  {
    # A Ground Object
    objType: "Sphere",
    center: [0.0, -1000.0, 0.0],
    radius: 1000.0,
    material: {
      matType: "Lambertian",
      texType: "SolidColor",
      albedo: [0.2, 0.2, 0.2],
      scale: 2.0,
    }
  },
  {
    # A Light Object
    objType: "Sphere",
    center: [7.5, 10.0, 3.0],
    radius: 2.0,
    material: {
      matType: "DiffuseLight",
      texType: "SolidColor",
      albedo: [1.0, 1.0, 1.0], # Property of SolidColor
      intensity: 9.2 # Property of DiffuseLight
    }
  },
  { # A Glass Sphere
    objType: "Sphere",
    center: [0.0, 5.0, 0.0],
    radius: 5.0,
    material: {
      matType: "Dielectric",
      refractionIdx: 1.4
    }
  },
  {
    objType: "Array:Sphere",
    objects: [
      { # Left Red Lambertian Sphere
        objType: "Sphere",
        center: [-2.5, 5.0, 0.0],
        radius: 2.5,
        material: {
          matType: "Lambertian",
          texType: "ImageTexture",
          filename: "images/earthmap.jpg"
          # albedo: [0.9, 0.1, 0.1]
        }
      },
      { # Right Green Metal Sphere
        objType: "Sphere",
        center: [2.5, 5.0, 0.0],
        radius: 2.5,
        material: {
          matType: "Metal",
          texType: "SolidColor",
          albedo: [0.2, 0.9, 0.2],
          fuzz: 0.0
        }
      }
    ]
  },
]
