constants:
  width: 1920
  height: 1080
  samplesPerPixel: 32
  maxDepth: 5000
  minDepth: 5

camera:
  lookFrom: [0.0, 6.0, 14.0]
  lookAt: [0.0, 0.0, 0.0]
  vup: [0.0, 1.0, 0.0]
  vfov: 90.0
  aspectRatio: 1.77777 # 1920.0 / 1080.0
  aperture: 0.1
  focusDistance: 10.0

world: [
  {
    # A Ground Object
    objType: "Sphere",
    center: [0.0, -1000.0, 0.0],
    radius: 1000.0,
    material: {
      matType: "Lambertian",
      texType: "SolidColor",
      texture: { albedo: [0.2, 0.2, 0.2] },
      # scale: 2.0,
    }
  },
  {
    # A Light Object
    objType: "Sphere",
    center: [7.5, 10.0, 3.0],
    radius: 2.0,
    material: {
      matType: "DiffuseLight",
      texType: "SolidColor",
      texture: { albedo: [1.0, 1.0, 1.0] }, # Property of SolidColor
      intensity: 9.2 # Property of DiffuseLight
    }
  },
  { # A Glass Sphere
    objType: "Sphere",
    center: [0.0, 5.0, 0.0],
    radius: 5.0,
    material: {
      matType: "Dielectric",
      texType: "SolidColor",
      texture: { albedo: [1.0, 1.0, 1.0] },
      refractionIdx: 1.4
    }
  },
  {
    objType: "Array:Sphere",
    objects: [
      { # Left Red Lambertian Sphere
        objType: "Sphere",
        center: [-2.5, 5.0, 0.0],
        radius: 2.5,
        material: {
          matType: "Lambertian",
          texType: "ImageTexture",
          texture: { filename: "images/earthmap.jpg" }
          # albedo: [0.9, 0.1, 0.1]
        }
      },
      { # Right Green Metal Sphere
        objType: "Sphere",
        center: [2.5, 5.0, 0.0],
        radius: 2.5,
        material: {
          matType: "GGX",
          texType: "SolidColor",
          texture: { albedo: [0.2, 0.9, 0.2] },
          reflectivity: 0.8,
          fuzz: 0.2,
          roughness: 0.4, # For GGX material
        }
      }
    ]
  },
]
