constants:
  width: 1920
  height: 1080
  samplesPerPixel: 32
  maxDepth: 5000
  minDepth: 500
  environmentMap: "skyboxes/starblack.jpg"
  environmentDistance: 100.0

camera:
  lookFrom: [0.0, 0.75, -8.0]
  lookAt: [0.0, 2.5, 0.0]
  vup: [0.0, 1.0, 0.0]
  vfov: 40.0
  aspectRatio: 1.777777
  aperture: 0.1
  focusDistance: 8.0

world: [
  {
    # Stormtroopers
    objType: "Mesh",
    position: [0.0, 0.0, 2.0], # Positionment and Rotation are absolute not relative!!!
    scalingFactor: 25.0,
    rotation: [-90.0, 0.0, 180.0], # 90, 90, 220 [ Yaw, Roll, Pitch ]
    filename: "models/stormtrooper.stl",
    material: {
      matType: "Plastic",
      texType: "SolidColor",
      texture: { albedo: [1.0, 1.0, 1.0] },
      fuzz: 0.0, # The amount of opaqueness, just like in metals
      reflectivity: 0.2 # How reflective you want your object to be, finetune this on each scene
    }
  },
  {
    # Stormtroopers
    objType: "Mesh",
    position: [0.0, 0.0, 2.0], # Positionment and Rotation are absolute not relative!!!
    scalingFactor: 25.0,
    rotation: [-90.0, 0.0, 180.0], # 90, 90, 220 [ Yaw, Roll, Pitch ]
    filename: "models/stormtrooper_body.stl",
    material: {
      matType: "Lambertian",
      texType: "SolidColor",
      texture: { albedo: [0.05, 0.05, 0.05] }
    }
  },
  {
    # Lights on top of the Stormtroopers
    objType: "XZRectangle",
    position: [5.0, 10.0, 5.0],
    width: 1.0,
    height: 50.0,
    material: {
      matType: "DiffuseLight",
      texType: "SolidColor",
      texture: { albedo: [0.0, 0.5, 1.0] },
      intensity: 5.0,
    }
  },
  {
    # Lights on top of the Stormtroopers
    objType: "XZRectangle",
    position: [0.0, 10.0, 5.0],
    width: 1.0,
    height: 50.0,
    material: {
      matType: "DiffuseLight",
      texType: "SolidColor",
      texture: { albedo: [0.0, 0.5, 1.0] },
      intensity: 5.0,
    }
  },
  {
    # Lights on top of the Stormtroopers
    objType: "XZRectangle",
    position: [-5.0, 10.0, 5.0],
    width: 1.0,
    height: 50.0,
    material: {
      matType: "DiffuseLight",
      texType: "SolidColor",
      texture: { albedo: [0.0, 0.5, 1.0] },
      intensity: 5.0,
    }
  },
  {
    # Lights on side of the Stormtroopers
    objType: "YZRectangle",
    position: [100.0, 0.0, 0.0],
    width: 20.0,
    height: 40.0,
    material: {
      matType: "DiffuseLight",
      texType: "SolidColor",
      texture: { albedo: [1.0, 0.1, 0.0] },
      intensity: 5.0,
    }
  },
  {
    # Lights on side of the Stormtroopers
    objType: "YZRectangle",
    position: [-100.0, 0.0, 0.0],
    width: 20.0,
    height: 40.0,
    material: {
      matType: "DiffuseLight",
      texType: "SolidColor",
      texture: { albedo: [1.0, 0.1, 0.0] },
      intensity: 5.0,
    }
  }
]
